repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: black-package
        files: ^package/
        args: ["--config=package/pyproject.toml"]

      - id: black
        name: black-webapp
        files: ^webapp/
        args: ["--config=webapp/pyproject.toml"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8-package
        files: ^package/
        entry: flake8p
        args: ["--toml-config=package/pyproject.toml"]
        additional_dependencies:
          - flake8-pyproject

      - id: flake8
        name: flake8-webapp
        files: ^webapp/
        entry: flake8p
        args: ["--toml-config=webapp/pyproject.toml"]
        additional_dependencies:
          - flake8-pyproject

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort-package
        files: ^package/
        args: ["--settings-path=package/pyproject.toml"]

      - id: isort
        name: isort-webapp
        files: ^webapp/
        args: ["--settings-path=webapp/pyproject.toml"]
